USE_CAMERA_STUB := false

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7x30
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_ARCH := arm
TARGET_CPU_VARIANT := cortex-a8
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_NEON := true
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_ARMV7A := true
TARGET_BOARD_PLATFORM_FPU := neon
TARGET_ARCH_VARIANT_FPU : = neon
TARGET_ARCH_VARIANT_CPU := cortex-a8
ARCH_ARM_HAVE_VFP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
USE_MALLOC_ALIGNMENT := 16
ARCH_ARM_HIGH_OPTIMIZATION := true

TARGET_PROVIDES_INIT_TARGET_RC := true

# Scorpion optimizations
TARGET_USE_SCORPION_BIONIC_OPTIMIZATION := true
TARGET_USE_SCORPION_PLD_SET := true
# Set to 9 for 8650A
TARGET_SCORPION_BIONIC_PLDOFFS := 6
TARGET_SCORPION_BIONIC_PLDSIZE := 128

TARGET_EXTRA_CFLAGS += $(call cc-option,-march=armv7-a -mtune=cortex-a8)
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp -march=armv7-a
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp -march=armv7-a

COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE -DREFRESH_RATE=60 -DQCOM_NO_SECURE_PLAYBACK 
COMMON_GLOBAL_CFLAGS += -DNO_UPDATE_PREVIEW -DNEEDS_VECTORIMPL_SYMBOLS

TARGET_SPECIFIC_HEADER_PATH := device/lge/m3s/include

TARGET_BOOTLOADER_BOARD_NAME := lge_m3s

TARGET_BOOTANIMATION_NAME := vertical-320x480

BOARD_USES_ADRENO_200 := true
TARGET_USES_GENLOCK := true
TARGET_USES_OVERLAY := false
TARGET_HAVE_BYPASS := false
TARGET_USES_SF_BYPASS := false
WEBCORE_INPAGE_VIDEO := true
TARGET_USES_C2D_COMPOSITION := true
TARGET_NO_HW_VSYNC := true
TARGET_QCOM_HDMI_OUT := false
USE_OPENGL_RENDERER := true
TARGET_GRALLOC_USES_ASHMEM := true
TARGET_USES_PMEM := true
BOARD_USES_PMEM_ADSP := true
BOARD_EGL_WORKAROUND_BUG_10194508 := true
TARGET_HAVE_TSLIB := false
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
TARGET_DISABLE_TRIPLE_BUFFERING := false
BOARD_ALLOW_EGL_HIBERNATION := true
BOARD_EGL_NEEDS_LEGACY_FB := true

JS_ENGINE := v8
HTTP := chrome
WITH_JIT := true
ENABLE_JSC_JIT := true
ENABLE_WEBGL := true
TARGET_FORCE_CPU_UPLOAD := true
WEBCORE_ACCELERATED_SCROLLING := true
ENABLE_WTF_USE_ACCELERATED_COMPOSITING := true

# Wifi Properties  
BOARD_HAS_QCOM_WLAN := true
BOARD_WLAN_DEVICE := qcwcn
WIFI_EXT_MODULE_PATH := /system/lib/modules/librasdioif.ko
WIFI_DRIVER_MODULE_PATH := /system/lib/modules/wlan.ko
WIFI_EXT_MODULE_NAME := librasdioif
WIFI_DRIVER_MODULE_NAME := wlan
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_wext
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WEXT_NO_COMBO_SCAN := true
WPA_BUILD_SUPPLICANT := true
WIFI_DRIVER_HAS_LGE_SOFTAP := true

BOARD_PREBUILT_LIBAUDIO := false
BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_LEGACY_ALSA_AUDIO := true
BOARD_HAVE_QCOM_FM := false
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true
BOARD_HAVE_BLUETOOTH_BCM := true
BLUETOOTH_HCIATTACH_USING_PROPERTY := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/lge/m3s/bluetooth
BOARD_BLUEDROID_VENDOR_CONF := device/lge/m3s/bluetooth/vnd_m3s.txt


BOARD_GLOBAL_CFLAGS += -DCHARGERMODE_CMDLINE_NAME='"lge.reboot"' -DCHARGERMODE_CMDLINE_VALUE='"pwroff"'



BOARD_EGL_CFG := device/lge/m3s/configs/egl.cfg


BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true
BOARD_USE_QCOM_PMEM := true
TARGET_USES_ION := false
BOARD_USES_LEGACY_QCOM := true
TARGET_QCOM_DISPLAY_VARIANT := legacy
TARGET_QCOM_MEDIA_VARIANT := legacy
TARGET_QCOM_AUDIO_VARIANT := caf
BOARD_HAVE_PRE_KITKAT_AUDIO_BLOB := true
BOARD_USES_AUDIO_LEGACY := false
BOARD_USES_ALSA_AUDIO := false
TARGET_QCOM_NO_SECURE_PLAYBACK := true

BOARD_USES_QCOM_LIBRPC := true
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := lge_m3s
# AMSS version to use for GPS
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000
BOARD_VENDOR_QCOM_AMSS_VERSION := 50000
 

COMMON_GLOBAL_CFLAGS += -DBINDER_COMPAT
TARGET_ENABLE_QC_AV_ENHANCEMENTS := true
BOARD_USES_QCOM_LEGACY_CAM_PARAMS := true
BOARD_USES_LEGACY_OVERLAY := true
BOARD_NEEDS_MEMORYHEAPPMEM := true
BOARD_CAMERA_USE_MM_HEAP := true
BOARD_CAMERA_USE_GETBUFFERINFO := true
TARGET_DISABLE_ARM_PIE := false

BOARD_USES_LEGACY_RIL := true

# Try to build the kernel
TARGET_KERNEL_CONFIG := lge_m3s-perf_defconfig
TARGET_KERNEL_SOURCE := /media/Sources/android_kernel_lge_m3s

BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom
BOARD_KERNEL_BASE := 0x00200000
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x01100000
BOARD_KERNEL_PAGESIZE := 4096

BOARD_KERNEL_RECOVERY_CMDLINE := $(BOARD_KERNEL_CMDLINE)
TARGET_PREBUILT_RECOVERY_KERNEL		:= device/lge/m3s/prebuilt/recovery_kernel
TARGET_RECOVERY_INITRC			:= device/lge/m3s/recovery/init.rc
RECOVERY_FSTAB_VERSION=2
TARGET_RECOVERY_FSTAB = device/lge/m3s/root/fstab.qcom

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p12
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_DATA_DEVICE := /dev/block/mmcblk0p13
BOARD_DATA_FILESYSTEM := ext4
BOARD_CACHE_DEVICE := /dev/block/mmcblk0p11
BOARD_CACHE_FILESYSTEM := ext4
BOARD_SDCARD_DEVICE_PRIMARY := /dev/block/mmcblk0
BOARD_SDCARD_DEVICE_SECONDARY := /dev/block/mmcblk1
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 377487360
BOARD_USERDATAIMAGE_PARTITION_SIZE := 947912704
BOARD_BOOTIMAGE_PARTITION_SIZE	:= 8388608
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 8388608
BOARD_FLASH_BLOCK_SIZE := 262144

TARGET_NO_BOOT := false
TARGET_NO_RECOVERY := false
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_NO_INITLOGO := true

BOARD_VOLD_MAX_PARTITIONS := 24
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/usb_mass_storage/lun%d/file"
TARGET_USE_CUSTOM_SECOND_LUN_NUM := 1

BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_USES_RECOVERY_CHARGEMODE := false

BOARD_USES_SECURE_SERVICES := true

TARGET_RELEASETOOLS_EXTENSIONS	:= device/lge/m3s/tools/ota_from_target_files

# Boot Animation
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true
TARGET_BOOTANIMATION_USE_RGB565 := true

BOARD_MOBILEDATA_INTERFACE_NAME = "rmnet0"

TARGET_ARCH_LOWMEM := true

# TWRP Recovery
DEVICE_RESOLUTION := 320x480
TW_INTERNAL_STORAGE_PATH := "/emmc"
TW_INTERNAL_STORAGE_MOUNT_POINT := "emmc"
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_CUSTOM_POWER_BUTTON := 107
TW_NO_REBOOT_BOOTLOADER := true
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_FLASH_FROM_STORAGE := true
TARGET_RECOVERY_LCD_BACKLIGHT_PATH := \"/sys/class/leds/lcd-backlight/brightness\"

BOARD_PREBUILT_LIBAUDIO := false
BOARD_WANTS_EMMC_BOOT := true
SKIP_SET_METADATA := true
USE_SET_METADATA := false
BOARD_USE_MHEAP_SCREENSHOT := true
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
TARGET_DISPLAY_INSECURE_MM_HEAP := true
TARGET_DISPLAY_USE_RETIRE_FENCE := true
