USE_CAMERA_STUB := false

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7x30
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
ARCH_ARM_HAVE_VFP := true
TARGET_ARCH_VARIANT_FPU := neon
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_PROVIDES_INIT_RC := true
TARGET_PROVIDES_INIT_TARGET_RC := true

# Scorpion optimizations
TARGET_USE_SCORPION_BIONIC_OPTIMIZATION := true
TARGET_USE_SCORPION_PLD_SET := true
# Set to 9 for 8650A
TARGET_SCORPION_BIONIC_PLDOFFS := 6
TARGET_SCORPION_BIONIC_PLDSIZE := 128

TARGET_EXTRA_CFLAGS += $(call cc-option,-march=armv7-a -mtune=cortex-a8)
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp

COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE -DREFRESH_RATE=60
COMMON_GLOBAL_CFLAGS += -DQCOM_ROTATOR_KERNEL_FORMATS
COMMON_GLOBAL_CFLAGS += -DBINDER_COMPAT

TARGET_SPECIFIC_HEADER_PATH := device/lge/m3s/include

TARGET_BOOTLOADER_BOARD_NAME := lge_m3s

TARGET_BOOTANIMATION_NAME := vertical-320x480

BOARD_USES_ADRENO_200 := true
TARGET_USES_GENLOCK := true
TARGET_USES_OVERLAY := false
TARGET_HAVE_BYPASS := false
TARGET_USES_SF_BYPASS := false
WEBCORE_INPAGE_VIDEO := true
TARGET_USES_C2D_COMPOSITION := true
TARGET_NO_HW_VSYNC := false
TARGET_QCOM_HDMI_OUT := false
USE_OPENGL_RENDERER := true
TARGET_GRALLOC_USES_ASHMEM := false
TARGET_HARDWARE_3D := false
TARGET_HAVE_TSLIB := true
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true

DYNAMIC_SHARED_LIBV8SO := true
JS_ENGINE := v8
HTTP := chrome
WITH_JIT := true
ENABLE_JSC_JIT := true
ENABLE_WEBGL := true
TARGET_FORCE_CPU_UPLOAD := true
WEBCORE_ACCELERATED_SCROLLING := true
ENABLE_WTF_USE_ACCELERATED_COMPOSITING := true

# Wifi Properties  
BOARD_HAS_QCOM_WLAN := true
BOARD_WLAN_DEVICE := qcwcn
WIFI_EXT_MODULE_PATH := /system/lib/modules/librasdioif.ko
WIFI_DRIVER_MODULE_PATH := /system/lib/modules/wlan.ko
WIFI_EXT_MODULE_NAME := librasdioif
WIFI_DRIVER_MODULE_NAME := wlan
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_wext
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := WEXT
BOARD_WEXT_NO_COMBO_SCAN := true


BOARD_USES_LEGACY_RIL := true

BOARD_USES_GENERIC_AUDIO := false
BOARD_HAVE_QCOM_FM := false
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true


BOARD_GLOBAL_CFLAGS += -DCHARGERMODE_CMDLINE_NAME='"lge.reboot"' -DCHARGERMODE_CMDLINE_VALUE='"pwroff"'



BOARD_EGL_CFG := device/lge/m3s/configs/egl.cfg


BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true
BOARD_USE_QCOM_PMEM := true
#BUILD_WITH_FULL_STAGEFRIGHT := true

BOARD_USES_QCOM_LIBRPC := true
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := lge_m3s
# AMSS version to use for GPS
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000
BOARD_VENDOR_QCOM_AMSS_VERSION := 50000

BOARD_CAMERA_USE_GETBUFFERINFO := true
BOARD_USE_CAF_LIBCAMERA := true

BOARD_OVERLAY_FORMAT_YCbCr_420_SP := true

# Try to build the kernel
TARGET_KERNEL_CONFIG := lge_m3s-perf_defconfig
TARGET_PREBUILT_KERNEL := device/lge/m3s/prebuilt/kernel
TARGET_KERNEL_SOURCE := kernel/lge/m3s

BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom
BOARD_KERNEL_BASE := 0x00200000
BOARD_FORCE_RAMDISK_ADDRESS := 0x01300000
BOARD_KERNEL_PAGESIZE := 4096

BOARD_KERNEL_RECOVERY_CMDLINE := $(BOARD_KERNEL_CMDLINE)
TARGET_PREBUILT_RECOVERY_KERNEL		:= device/lge/m3s/prebuilt/recovery_kernel
TARGET_RECOVERY_INITRC			:= device/lge/m3s/recovery/init.rc
BOARD_CUSTOM_GRAPHICS			:= ../../../device/lge/m3s/recovery/graphics.c
BOARD_CUSTOM_RECOVERY_KEYMAPPING        := ../../device/lge/m3s/recovery/recovery_keys.c

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p12
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_DATA_DEVICE := /dev/block/mmcblk0p13
BOARD_DATA_FILESYSTEM := ext4
BOARD_CACHE_DEVICE := /dev/block/mmcblk0p11
BOARD_CACHE_FILESYSTEM := ext4
BOARD_SDCARD_DEVICE_PRIMARY := /dev/block/mmcblk0
BOARD_SDCARD_DEVICE_SECONDARY := /dev/block/mmcblk1
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 377487360
BOARD_USERDATAIMAGE_PARTITION_SIZE := 947912704
BOARD_BOOTIMAGE_PARTITION_SIZE	:= 8388608
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 8388608
BOARD_FLASH_BLOCK_SIZE := 262144

TARGET_NO_BOOT := false
TARGET_NO_RECOVERY := false
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

BOARD_VOLD_MAX_PARTITIONS := 24
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/usb_mass_storage/lun%d/file"
TARGET_USE_CUSTOM_SECOND_LUN_NUM := 1

BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_USES_RECOVERY_CHARGEMODE := false

BOARD_USES_SECURE_SERVICES := true

# Enable NFC
BOARD_HAVE_NFC := true

NFC_BUILD_VARIANT := debug

TARGET_RELEASETOOL_OTA_FROM_TARGET_SCRIPT	:= device/lge/m3s/tools/ota_from_target_files

# Boot Animation
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true
TARGET_BOOTANIMATION_USE_RGB565 := true

# TWRP Recovery
DEVICE_RESOLUTION := 320x480
TW_INTERNAL_STORAGE_PATH := "/emmc"
TW_INTERNAL_STORAGE_MOUNT_POINT := "emmc"
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_CUSTOM_POWER_BUTTON := 107
TW_NO_REBOOT_BOOTLOADER := true
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_FLASH_FROM_STORAGE := true
